[build]
  publish = "dist/"
  command = "yarn build:netlify"

# These build env vars are specific only to Netlify.
[build.environment]
  YARN_VERSION = "3.2.1"
  CI = "true"

[functions]
  directory = "src/functions"

[[redirects]]
  from = "/*"
  to = "index.html"
  status = 200

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-Content-Type-Options = "nosniff"

[dev]
  command = "yarn start"
  framework = "#custom"
  port = 8888
  targetPort = 4173
  functionsPort = 59199
  autoLaunch = false
