specVersion: 0.0.9
schema:
  file: ../schema.graphql
dataSources:
  ###
  # INITIALIZATION
  ###
  - kind: ethereum/contract
    name: InitVersion
    network: arbitrum-one
    source:
      address: "0xD1A0060ba708BC4BCD3DA6C37EFa8deDF015FB70"
      abi: Reseed
      startBlock: 261772156 # Reseed
      endBlock: 261772156 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Version
      abis:
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      blockHandlers:
        - handler: handleInitVersion
          filter:
            kind: once
      file: ../src/utils/constants/Version.ts
  - kind: ethereum/contract
    name: InitInit
    network: arbitrum-one
    source:
      address: "0xD1A0060ba708BC4BCD3DA6C37EFa8deDF015FB70"
      abi: Reseed
      startBlock: 261772156 # Reseed
      endBlock: 261772156 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Version
      abis:
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      blockHandlers:
        - handler: init
          filter:
            kind: once
      file: ../src/utils/b3-migration/Init.ts
  ###
  # BEAN TOKEN
  ###
  - kind: ethereum/contract
    name: BeanToken
    network: arbitrum-one
    source:
      address: "0xBEA0005B8599265D41256905A9B3073D397812E4"
      abi: ERC20
      startBlock: 261772156 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Bean
      abis:
        - name: ERC20
          file: ../../subgraph-core/abis/ERC20.json
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ../src/handlers/BeanHandler.ts
  ###
  # BEANSTALK PROTOCOL
  ###
  - kind: ethereum/contract
    name: Beanstalk
    network: arbitrum-one
    source:
      address: "0xD1A0060ba708BC4BCD3DA6C37EFa8deDF015FB70"
      abi: Reseed
      startBlock: 261772156 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Bean
      abis:
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
        - name: BeanstalkPrice
          file: ../../subgraph-core/abis/BeanstalkPrice.json
        - name: ERC20
          file: ../../subgraph-core/abis/ERC20.json
      eventHandlers:
        - event: DewhitelistToken(indexed address)
          handler: handleDewhitelistToken
        - event: Chop(indexed address,indexed address,uint256,uint256)
          handler: handleChop
        - event: Convert(indexed address,address,address,uint256,uint256)
          handler: handleConvert
        - event: Sunrise(indexed uint256)
          handler: handleSunrise
        - event: Shipped(indexed uint32,uint256)
          handler: handleShipped
      file: ../src/handlers/BeanstalkHandler.ts
  - kind: ethereum/contract
    name: WellTWAP
    network: arbitrum-one
    source:
      address: "0xD1A0060ba708BC4BCD3DA6C37EFa8deDF015FB70"
      abi: Reseed
      startBlock: 261772156 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Bean
      abis:
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
        - name: Well
          file: ../../subgraph-core/abis/Well.json
      eventHandlers:
        - event: WellOracle(indexed uint32,address,int256,bytes)
          handler: handleWellOracle
      file: ../src/handlers/BeanstalkHandler.ts
  ###
  # POOLS
  ###
  - kind: ethereum/contract
    name: BeanWETH
    network: arbitrum-one
    source:
      address: "0xBeA00Aa8130aCaD047E137ec68693C005f8736Ce"
      abi: Well
      startBlock: 261772156 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: Well
          file: ../../subgraph-core/abis/Well.json
        - name: BeanstalkPrice
          file: ../../subgraph-core/abis/BeanstalkPrice.json
        - name: ERC20
          file: ../../subgraph-core/abis/ERC20.json
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      eventHandlers:
        - event: AddLiquidity(uint256[],uint256,address)
          handler: handleAddLiquidity
        - event: RemoveLiquidity(uint256,uint256[],address)
          handler: handleRemoveLiquidity
        - event: RemoveLiquidityOneToken(uint256,address,uint256,address)
          handler: handleRemoveLiquidityOneToken
        - event: Swap(address,address,uint256,uint256,address)
          handler: handleSwap
        - event: Shift(uint256[],address,uint256,address)
          handler: handleShift
        - event: Sync(uint256[],uint256,address)
          handler: handleSync
      file: ../src/handlers/BeanWellHandler.ts
  - kind: ethereum/contract
    name: BeanwstETH
    network: arbitrum-one
    source:
      address: "0xBEa00BbE8b5da39a3F57824a1a13Ec2a8848D74F"
      abi: Well
      startBlock: 261772156 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: Well
          file: ../../subgraph-core/abis/Well.json
        - name: BeanstalkPrice
          file: ../../subgraph-core/abis/BeanstalkPrice.json
        - name: ERC20
          file: ../../subgraph-core/abis/ERC20.json
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      eventHandlers:
        - event: AddLiquidity(uint256[],uint256,address)
          handler: handleAddLiquidity
        - event: RemoveLiquidity(uint256,uint256[],address)
          handler: handleRemoveLiquidity
        - event: RemoveLiquidityOneToken(uint256,address,uint256,address)
          handler: handleRemoveLiquidityOneToken
        - event: Swap(address,address,uint256,uint256,address)
          handler: handleSwap
        - event: Shift(uint256[],address,uint256,address)
          handler: handleShift
        - event: Sync(uint256[],uint256,address)
          handler: handleSync
      file: ../src/handlers/BeanWellHandler.ts
  - kind: ethereum/contract
    name: BeanweETH
    network: arbitrum-one
    source:
      address: "0xBeA00Cc9F93E9a8aC0DFdfF2D64Ba38eb9C2e48c"
      abi: Well
      startBlock: 261772156 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: Well
          file: ../../subgraph-core/abis/Well.json
        - name: BeanstalkPrice
          file: ../../subgraph-core/abis/BeanstalkPrice.json
        - name: ERC20
          file: ../../subgraph-core/abis/ERC20.json
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      eventHandlers:
        - event: AddLiquidity(uint256[],uint256,address)
          handler: handleAddLiquidity
        - event: RemoveLiquidity(uint256,uint256[],address)
          handler: handleRemoveLiquidity
        - event: RemoveLiquidityOneToken(uint256,address,uint256,address)
          handler: handleRemoveLiquidityOneToken
        - event: Swap(address,address,uint256,uint256,address)
          handler: handleSwap
        - event: Shift(uint256[],address,uint256,address)
          handler: handleShift
        - event: Sync(uint256[],uint256,address)
          handler: handleSync
      file: ../src/handlers/BeanWellHandler.ts
  - kind: ethereum/contract
    name: BeanWBTC
    network: arbitrum-one
    source:
      address: "0xBea00DDe4b34ACDcB1a30442bD2B39CA8Be1b09c"
      abi: Well
      startBlock: 261772156 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: Well
          file: ../../subgraph-core/abis/Well.json
        - name: BeanstalkPrice
          file: ../../subgraph-core/abis/BeanstalkPrice.json
        - name: ERC20
          file: ../../subgraph-core/abis/ERC20.json
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      eventHandlers:
        - event: AddLiquidity(uint256[],uint256,address)
          handler: handleAddLiquidity
        - event: RemoveLiquidity(uint256,uint256[],address)
          handler: handleRemoveLiquidity
        - event: RemoveLiquidityOneToken(uint256,address,uint256,address)
          handler: handleRemoveLiquidityOneToken
        - event: Swap(address,address,uint256,uint256,address)
          handler: handleSwap
        - event: Shift(uint256[],address,uint256,address)
          handler: handleShift
        - event: Sync(uint256[],uint256,address)
          handler: handleSync
      file: ../src/handlers/BeanWellHandler.ts
  - kind: ethereum/contract
    name: BeanUSDC
    network: arbitrum-one
    source:
      address: "0xBea00ee04D8289aEd04f92EA122a96dC76A91bd7"
      abi: Well
      startBlock: 261772156 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: Well
          file: ../../subgraph-core/abis/Well.json
        - name: BeanstalkPrice
          file: ../../subgraph-core/abis/BeanstalkPrice.json
        - name: ERC20
          file: ../../subgraph-core/abis/ERC20.json
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      eventHandlers:
        - event: AddLiquidity(uint256[],uint256,address)
          handler: handleAddLiquidity
        - event: RemoveLiquidity(uint256,uint256[],address)
          handler: handleRemoveLiquidity
        - event: RemoveLiquidityOneToken(uint256,address,uint256,address)
          handler: handleRemoveLiquidityOneToken
        - event: Swap(address,address,uint256,uint256,address)
          handler: handleSwap
        - event: Shift(uint256[],address,uint256,address)
          handler: handleShift
        - event: Sync(uint256[],uint256,address)
          handler: handleSync
      file: ../src/handlers/BeanWellHandler.ts
  - kind: ethereum/contract
    name: BeanUSDT
    network: arbitrum-one
    source:
      address: "0xbEA00fF437ca7E8354B174339643B4d1814bED33"
      abi: Well
      startBlock: 261772156 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Pool
      abis:
        - name: Well
          file: ../../subgraph-core/abis/Well.json
        - name: BeanstalkPrice
          file: ../../subgraph-core/abis/BeanstalkPrice.json
        - name: ERC20
          file: ../../subgraph-core/abis/ERC20.json
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      eventHandlers:
        - event: AddLiquidity(uint256[],uint256,address)
          handler: handleAddLiquidity
        - event: RemoveLiquidity(uint256,uint256[],address)
          handler: handleRemoveLiquidity
        - event: RemoveLiquidityOneToken(uint256,address,uint256,address)
          handler: handleRemoveLiquidityOneToken
        - event: Swap(address,address,uint256,uint256,address)
          handler: handleSwap
        - event: Shift(uint256[],address,uint256,address)
          handler: handleShift
        - event: Sync(uint256[],uint256,address)
          handler: handleSync
      file: ../src/handlers/BeanWellHandler.ts
  ###
  # PEG CROSS CHECK PER BLOCK
  ###
  - kind: ethereum/contract
    name: CrossCheck
    network: arbitrum-one
    source:
      address: "0xC218F5a782b0913931DCF502FA2aA959b36Ac9E7"
      abi: BeanstalkPrice
      startBlock: 575757575 # Reseed Unpause (TODO)
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - BeanCross
      abis:
        - name: BeanstalkPrice
          file: ../../subgraph-core/abis/BeanstalkPrice.json
      blockHandlers:
        - handler: handleBlock
          filter:
            kind: polling
            every: 40 # 10 seconds on arbitrum
      file: ../src/handlers/CrossHandler.ts
# features:
#   - grafting
# graft:
#   base: QmYnY2GzZbwTqot3H4jAV83mPbGTnBavdbB8bVXYxJzLUd
#   block: 20291520
