# This file exists solely for the purpose of facilitating all codegen in a shared location such that all ABIs
# or templates are expanded independently of being used in all chains. Most of the information here is irrelevant,
# the only important part is in the `abis` and `templates` sections.
#  - For abis, its only the list of abis that is relevant. The name of the dataSource is also visible.
#  - For templates, it is only the name of the template that is relevant.
specVersion: 0.0.9
schema:
  file: ../schema.graphql
dataSources:
  - kind: ethereum/contract
    name: Basin-ABIs
    network: not_relevant
    source:
      address: "0xBA51AAAA95aeEFc1292515b36D86C51dC7877773"
      abi: Aquifer
      startBlock: 17977922
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Aquifer
      abis:
        - name: Aquifer
          file: ../../subgraph-core/abis/Aquifer.json
        - name: ERC20
          file: ../../subgraph-core/abis/ERC20.json
        - name: Beanstalk
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
        - name: Well
          file: ../../subgraph-core/abis/Well.json
        - name: CurvePrice
          file: ../../subgraph-core/abis/CurvePrice.json
        - name: BeanstalkPrice
          file: ../../subgraph-core/abis/BeanstalkPrice.json
      blockHandlers:
        - handler: handleInitVersion
          filter:
            kind: once
      file: ../src/utils/constants/Version.ts
templates:
  - kind: ethereum/contract
    name: Well
    network: not_relevant
    source:
      abi: Well
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.7
      language: wasm/assemblyscript
      entities:
        - Well
      abis:
        - name: Well
          file: ../../subgraph-core/abis/Well.json
      blockHandlers:
        - handler: handleInitVersion
          filter:
            kind: once
      file: ../src/utils/constants/Version.ts
