specVersion: 0.0.9
schema:
  file: ../schema.graphql
dataSources:
  ###
  # L1 -> L2 MIGRATION
  ###
  # (TODO)

  ###
  # INITIALIZATION
  ###
  - kind: ethereum/contract
    name: Version
    network: arbitrum-one
    source:
      address: "0xD1A0060ba708BC4BCD3DA6C37EFa8deDF015FB70"
      abi: Reseed
      startBlock: 585858585858 # Reseed
      endBlock: 585858585858 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Version
      abis:
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      blockHandlers:
        - handler: handleInitVersion
          filter:
            kind: once
      file: ../src/utils/constants/Version.ts
  ###
  # SILO
  ###
  - kind: ethereum/contract
    name: Silo
    network: arbitrum-one
    source:
      address: "0xD1A0060ba708BC4BCD3DA6C37EFa8deDF015FB70"
      abi: Reseed
      startBlock: 585858585858 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Silo
      abis:
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      eventHandlers:
        - event: AddDeposit(indexed address,indexed address,int96,uint256,uint256)
          handler: handleAddDeposit
        - event: RemoveDeposit(indexed address,indexed address,int96,uint256,uint256)
          handler: handleRemoveDeposit
        - event: RemoveDeposits(indexed address,indexed address,int96[],uint256[],uint256,uint256[])
          handler: handleRemoveDeposits
        - event: Convert(indexed address,address,address,uint256,uint256)
          handler: handleConvert
        - event: StalkBalanceChanged(indexed address,int256,int256)
          handler: handleStalkBalanceChanged
        - event: Plant(indexed address,uint256)
          handler: handlePlant
        - event: WhitelistToken(indexed address,bytes4,uint32,uint256,uint128,uint64)
          handler: handleWhitelistToken
        - event: DewhitelistToken(indexed address)
          handler: handleDewhitelistToken
        - event: UpdatedStalkPerBdvPerSeason(indexed address,uint32,uint32)
          handler: handleUpdatedStalkPerBdvPerSeason
      file: ../src/handlers/SiloHandler.ts
  ###
  # SEED GAUGE
  ###
  - kind: ethereum/contract
    name: SeedGauge
    network: arbitrum-one
    source:
      address: "0xD1A0060ba708BC4BCD3DA6C37EFa8deDF015FB70"
      abi: Reseed
      startBlock: 585858585858 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - SeedGauge
      abis:
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
        - name: BeanstalkPrice
          file: ../../subgraph-core/abis/BeanstalkPrice.json
      eventHandlers:
        - event: BeanToMaxLpGpPerBdvRatioChange(indexed uint256,uint256,int80)
          handler: handleBeanToMaxLpGpPerBdvRatioChange
        - event: GaugePointChange(indexed uint256,indexed address,uint256)
          handler: handleGaugePointChange
        - event: UpdateAverageStalkPerBdvPerSeason(uint256)
          handler: handleUpdateAverageStalkPerBdvPerSeason
        - event: FarmerGerminatingStalkBalanceChanged(indexed address,int256,uint8)
          handler: handleFarmerGerminatingStalkBalanceChanged
        - event: TotalGerminatingBalanceChanged(uint256,indexed address,int256,int256)
          handler: handleTotalGerminatingBalanceChanged
        - event: TotalGerminatingStalkChanged(uint256,int256)
          handler: handleTotalGerminatingStalkChanged
        - event: TotalStalkChangedFromGermination(int256,int256)
          handler: handleTotalStalkChangedFromGermination
        - event: UpdatedOptimalPercentDepositedBdvForToken(indexed address,uint64)
          handler: handleUpdatedOptimalPercentDepositedBdvForToken
      file: ../src/handlers/GaugeHandler.ts
  ###
  # FIELD
  ###
  - kind: ethereum/contract
    name: Field
    network: arbitrum-one
    source:
      address: "0xD1A0060ba708BC4BCD3DA6C37EFa8deDF015FB70"
      abi: Reseed
      startBlock: 585858585858 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Field
      abis:
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
        - name: BeanstalkPrice
          file: ../../subgraph-core/abis/BeanstalkPrice.json
      eventHandlers:
        - event: Sow(indexed address,uint256,uint256,uint256,uint256)
          handler: handleSow
        - event: Harvest(indexed address,uint256,uint256[],uint256)
          handler: handleHarvest
        - event: PlotTransfer(indexed address,indexed address,uint256,indexed uint256,uint256)
          handler: handlePlotTransfer
        - event: TemperatureChange(indexed uint256,uint256,int8,uint256)
          handler: handleTemperatureChange
      file: ../src/handlers/FieldHandler.ts
  ###
  # MARKETPLACE
  ###
  - kind: ethereum/contract
    name: Marketplace
    network: arbitrum-one
    source:
      address: "0xD1A0060ba708BC4BCD3DA6C37EFa8deDF015FB70"
      abi: Reseed
      startBlock: 585858585858 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - PodMarketplace
      abis:
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      eventHandlers:
        - event: PodListingCreated(indexed address,uint256,uint256,uint256,uint256,uint24,uint256,uint256,uint8)
          handler: handlePodListingCreated
        - event: PodListingFilled(indexed address,indexed address,uint256,uint256,uint256,uint256,uint256)
          handler: handlePodListingFilled
        - event: PodOrderCreated(indexed address,bytes32,uint256,uint256,uint24,uint256,uint256)
          handler: handlePodOrderCreated
        - event: PodOrderFilled(indexed address,indexed address,bytes32,uint256,uint256,uint256,uint256,uint256)
          handler: handlePodOrderFilled
        - event: PodListingCancelled(indexed address,uint256,uint256)
          handler: handlePodListingCancelled
        - event: PodOrderCancelled(indexed address,bytes32)
          handler: handlePodOrderCancelled
      file: ../src/handlers/MarketplaceHandler.ts
  ###
  # FERTILIZER
  ###
  - kind: ethereum/contract
    name: Fertilizer-1155
    network: arbitrum-one
    source:
      address: "0x2D5E484Dd7D43dFE32BF1Ed9fE6517b64F13Ea51"
      abi: Fertilizer
      startBlock: 585858585858 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Fertilizer
      abis:
        - name: Fertilizer
          file: ../../subgraph-core/abis/Fertilizer.json
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      eventHandlers:
        - event: TransferBatch(indexed address,indexed address,indexed address,uint256[],uint256[])
          handler: handleTransferBatch
        - event: TransferSingle(indexed address,indexed address,indexed address,uint256,uint256)
          handler: handleTransferSingle
      file: ../src/handlers/BarnHandler.ts
  - kind: ethereum/contract
    name: Fertilizer-Beanstalk
    network: arbitrum-one
    source:
      address: "0xD1A0060ba708BC4BCD3DA6C37EFa8deDF015FB70"
      abi: Reseed
      startBlock: 585858585858 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Chop
      abis:
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      eventHandlers:
        - event: Chop(indexed address,indexed address,uint256,uint256)
          handler: handleChop
        - event: ChangeUnderlying(indexed address,int256)
          handler: handleChangeUnderlying
      file: ../src/handlers/BarnHandler.ts
  ###
  # SEASON
  ###
  - kind: ethereum/contract
    name: Season
    network: arbitrum-one
    source:
      address: "0xD1A0060ba708BC4BCD3DA6C37EFa8deDF015FB70"
      abi: Reseed
      startBlock: 585858585858 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Season
      abis:
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
        - name: BeanstalkPrice
          file: ../../subgraph-core/abis/BeanstalkPrice.json
      eventHandlers:
        - event: Shipped(indexed uint32,uint256)
          handler: handleShipped
        - event: Receipt(indexed uint8,uint256,bytes)
          handler: handleReceipt
        - event: WellOracle(indexed uint32,address,int256,bytes)
          handler: handleWellOracle
        - event: Soil(indexed uint32,uint256)
          handler: handleSoil
        - event: Incentivization(indexed address,uint256)
          handler: handleIncentive
      file: ../src/handlers/SeasonHandler.ts
  ###
  # BEAN ERC20
  ###
  - kind: ethereum/contract
    name: Bean-Replanted
    network: arbitrum-one
    source:
      address: "0xBEA0005B8599265D41256905A9B3073D397812E4"
      abi: ERC20
      startBlock: 585858585858 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - Season
      abis:
        - name: ERC20
          file: ../../subgraph-core/abis/ERC20.json
      eventHandlers:
        - event: Transfer(indexed address,indexed address,uint256)
          handler: handleTransfer
      file: ../src/handlers/BeanHandler.ts
  ###
  # FARM BALANCE
  ###
  - kind: ethereum/contract
    name: Farm
    network: arbitrum-one
    source:
      address: "0xD1A0060ba708BC4BCD3DA6C37EFa8deDF015FB70"
      abi: Reseed
      startBlock: 585858585858 # Reseed
    mapping:
      kind: ethereum/events
      apiVersion: 0.0.6
      language: wasm/assemblyscript
      entities:
        - SiloAsset
      abis:
        - name: Reseed
          file: ../../subgraph-core/abis/Beanstalk/Beanstalk-BIP50.json
      eventHandlers:
        - event: InternalBalanceChanged(indexed address,indexed address,int256)
          handler: handleInternalBalanceChanged
      file: ../src/handlers/FarmHandler.ts
# features:
#   - grafting
# graft:
#   base: QmUqT47H7o3gcZ2mHRJf2J5hpitWDYxsMmacGeuvo1wKU7
#   block: 19927630
